// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Snappet_Be.Models;

public partial class AdminAction
{
    public int ActionId { get; set; }

    public int AdminId { get; set; }

    public string ActionType { get; set; }

    public int? EntityId { get; set; }

    public string EntityType { get; set; }

    public DateTime? Timestamp { get; set; }

    public virtual AdminUser Admin { get; set; }
}