// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Snappet_Be.Models;

public partial class AiAnalysis
{
    public int AnalysisId { get; set; }

    public int PhotoId { get; set; }

    public string Emotion { get; set; }

    public double ConfidenceScore { get; set; }

    public DateTime? AnalyzedAt { get; set; }

    public virtual Photo Photo { get; set; }
}