// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Snappet_Be.Models;

public partial class Membership
{
    public int MembershipId { get; set; }

    public int UserId { get; set; }

    public string PackageName { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public DateTime? PurchasedAt { get; set; }

    public virtual User User { get; set; }
}