// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Snappet_Be.Models;

public partial class Photo
{
    public int PhotoId { get; set; }

    public int PetId { get; set; }

    public int OwnerId { get; set; }

    public string PhotoUrl { get; set; }

    public string Tags { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<AiAnalysis> AiAnalyses { get; set; } = new List<AiAnalysis>();

    public virtual User Owner { get; set; }

    public virtual Pet Pet { get; set; }

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
}