// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductManagement.Repository.BusinessModels;

public partial class Order
{
    public int OrderId { get; set; }

    public int UserId { get; set; }

    public string Details { get; set; }

    public string Status { get; set; }

    public int PackageId { get; set; }

    public double Price { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual User User { get; set; }
}