// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductManagement.Repository.BusinessModels;

public partial class PetCategory
{
    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public string Description { get; set; }

    public string Photo { get; set; }

    public virtual ICollection<Pet> Pets { get; set; } = new List<Pet>();
}