// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductManagement.Repository.BusinessModels;

public partial class Report
{
    public int ReportId { get; set; }

    public int GeneratedBy { get; set; }

    public string ReportType { get; set; }

    public DateTime GeneratedAt { get; set; }

    public virtual AdminUser GeneratedByNavigation { get; set; }
}