// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductManagement.Repository.Models;

public partial class Emotion
{
    public int EmotionId { get; set; }

    public string TagName { get; set; }

    public virtual ICollection<PostEmotion> PostEmotions { get; set; } = new List<PostEmotion>();
}