// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductManagement.Repository.Models;

public partial class PostEmotion
{
    public int PostEmotionId { get; set; }

    public int EmotionId { get; set; }

    public virtual Emotion Emotion { get; set; }

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
}